---
title: "NBA project"
output: pdf_document
date: "2022-09-29"
---

```{r}
#library(dplyr)
```

lien Data :
https://www.kaggle.com/datasets/justinas/nba-players-data
```{r}
# nba = read.csv(file.choose(), sep = ",")
# nba
# attach(nba)
```




```{r}
#names(nba)=c("ID","Playeur","Team","Age","Height","Weight","College","Country","Draft_Year","draft_Round","Draft_Number","Game_Played","Pts_Avg","Reb_Avg","Assist_Avg","Net_Rating","Oreb_Pct","Dreb_Pct","Usg_Pct", "Ts_Pct","Ast_Pct","Season")
```



```{r}
#filter(nba,nba$season=="1996-97")
```

```{r}
# table = filter(nba,nba$player_name=="A.C. Green")
# length(table$player_name)
# table$season
```


```{r}
# test = data.frame()
# for (i in year) {
#     for (j in team) {
#     test2 = filter( nba,nba$season== i
#                     & 
#                   nba$team_abbreviation==j
#                    )
#     
#     test=rbind(test,test2)
#     }
# }
# 
# test
```



```{r}
# year_v = c(year,year) #values
# year_k = c("all", year) #key
# my_list = setNames(year_v,year_k)
# my_list
```



```{r}
#library("car")
```

```{r}
# filter( nba,nba$season== "1996-97"
#                     & 
#                   nba$team_abbreviation=="ATL"
#                    )
```


```{r}
# key <- c("Points", "rebonds", "Passes décisives","taille","poids")
# value <- c("pts","reb","ast","player_height","player_weight")
# my_list2 <- list()                     
# for(i in 1:length(key)) {             
#   my_list2[key[i]] <- value[i]
# }
# my_list2=setNames(value,key) #Plus Fastoche
```

```{r}
# table = filter(nba,nba$player_name=="Eldridge Recasner")
# table
```





